/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class joxy_utils_JoxyGraphics */

#ifndef _Included_joxy_utils_JoxyGraphics
#define _Included_joxy_utils_JoxyGraphics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     joxy_utils_JoxyGraphics
 * Method:    drawStringNative
 * Signature: (Ljava/awt/Graphics;Ljava/lang/Class;Ljava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_joxy_utils_JoxyGraphics_drawStringNative
  (JNIEnv *, jclass, jobject, jclass, jstring, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
