/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class joxy_utils_JoxyGraphics */

#ifndef _Included_joxy_utils_JoxyGraphics
#define _Included_joxy_utils_JoxyGraphics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     joxy_utils_JoxyGraphics
 * Method:    drawStringNative
 * Signature: (Ljava/lang/String;Ljava/awt/image/BufferedImage;)V
 */
JNIEXPORT void JNICALL Java_joxy_utils_JoxyGraphics_drawStringNative
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
