/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class joxy_JoxyFileChooserUI */

#ifndef _Included_joxy_JoxyFileChooserUI
#define _Included_joxy_JoxyFileChooserUI
#ifdef __cplusplus
extern "C" {
#endif
#undef joxy_JoxyFileChooserUI_space
#define joxy_JoxyFileChooserUI_space 10L
#ifdef __cplusplus
}
#endif
#endif
