/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class joxy_utils_JoxyGraphics */

#ifndef _Included_joxy_utils_JoxyGraphics
#define _Included_joxy_utils_JoxyGraphics
#ifdef __cplusplus
extern "C" {
#endif
#undef joxy_utils_JoxyGraphics_NATIVE_TEXT_RENDERING
#define joxy_utils_JoxyGraphics_NATIVE_TEXT_RENDERING 1L
#undef joxy_utils_JoxyGraphics_TEXT_CACHING
#define joxy_utils_JoxyGraphics_TEXT_CACHING 0L
/*
 * Class:     joxy_utils_JoxyGraphics
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_joxy_utils_JoxyGraphics_initializeNative
  (JNIEnv *, jclass);

/*
 * Class:     joxy_utils_JoxyGraphics
 * Method:    drawStringNative
 * Signature: (Ljava/lang/String;Ljava/awt/image/BufferedImage;IILjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_joxy_utils_JoxyGraphics_drawStringNative
  (JNIEnv *, jclass, jstring, jobject, jint, jint, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
